name: Pull Request Target

on: pull_request_target

jobs:
  pull-request:
    name: Pull Request Target

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout target
        uses: actions/checkout@v4
        with:
          path: target

      - name: Checkout merge
        uses: actions/checkout@v4
        with:
          path: merge
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Analyze target/content.txt
        uses: actions/github-script@v7
        with:
          script: |
            const pullRequest = require('./target/.github/workflows/scripts/pull-request.js')
            await pullRequest({ github, context, core }, "target", "pull-request-target-target");

      - name: Analyze merge/content.txt
        uses: actions/github-script@v7
        with:
          script: |
            const pullRequest = require('./target/.github/workflows/scripts/pull-request.js')
            await pullRequest({ github, context, core }, "merge", "pull-request-target-merge");
