name: Pull Request

on: pull_request

jobs:
  pull-request:
    name: Pull Request

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Analyze content.txt
      id: analyze
      uses: actions/github-script@v7
      with:
        script: |
          const pullRequest = require('./.github/workflows/scripts/pull-request.js')
          await pullRequest({ github, context, core }, "", null);

    - if: ${{ steps.analyze.outputs.FOO == 'true' }}
      run:
        touch foo.txt

    - if: ${{ steps.analyze.outputs.FOO == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: foo
        path: foo.txt
        if-no-files-found: error
        overwrite: true
