name: Pull Request

on: pull_request

jobs:
  pull-request:
    name: Pull Request

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Analyze content.txt
      uses: actions/github-script@v7
      with:
        script: |
          const pullRequest = require('./.github/workflows/scripts/pull-request.js')
          await pullRequest({ github, context, core }, "", "pull-request");
